// Rock Catcher owns its state, controls, animation loop, and saved high score.
const board=document.getElementById('game-board'),player=document.getElementById('player'),scoreEl=document.getElementById('score'),timeEl=document.getElementById('time'),bestEl=document.getElementById('best-score'),startBtn=document.getElementById('start-game'),pauseBtn=document.getElementById('pause-game'),overlay=document.getElementById('game-overlay'),overlayStart=document.getElementById('overlay-start'),overlayTitle=document.getElementById('overlay-title'),overlayCopy=document.getElementById('overlay-copy'),palette=['#e96383','#ab82c5','#f2a779','#73a9b4','#d8bd57','#819d85'];
let rocks=[],score=0,playerX=.5,running=false,paused=false,elapsed=0,spawnClock=0,previousTime=0,animationId=0,best=Number(localStorage.getItem('charvi-rock-best')||0);bestEl.textContent=best;
function placePlayer(){const max=board.clientWidth-player.offsetWidth;player.style.left=`${Math.max(0,Math.min(max,playerX*max))}px`;player.style.transform='none'}function movePlayer(n){if(!running||paused)return;playerX=Math.max(0,Math.min(1,playerX+n));placePlayer()}
function spawnRock(){const el=document.createElement('div');el.className='rock';el.style.background=palette[Math.floor(Math.random()*palette.length)];board.append(el);const size=34+Math.random()*16;el.style.width=el.style.height=`${size}px`;rocks.push({el,x:Math.random()*(board.clientWidth-size),y:-size,size,speed:145+Math.random()*85+elapsed*2.2,rotation:Math.random()*180})}function removeRock(r){r.el.remove();rocks.splice(rocks.indexOf(r),1)}
function finishGame(){running=paused=false;cancelAnimationFrame(animationId);rocks.forEach(r=>r.el.remove());rocks=[];pauseBtn.disabled=true;pauseBtn.textContent='Pause';if(score>best){best=score;bestEl.textContent=best;localStorage.setItem('charvi-rock-best',best);overlayTitle.textContent='New high score!'}else overlayTitle.textContent='Snack time over!';overlayCopy.textContent=`You caught ${score} rock${score===1?'':'s'}. Ready for another round?`;overlayStart.textContent='Play again';overlay.classList.remove('hidden')}
function startGame(){rocks.forEach(r=>r.el.remove());rocks=[];score=elapsed=0;spawnClock=.6;playerX=.5;scoreEl.textContent='0';timeEl.textContent='30';running=true;paused=false;pauseBtn.disabled=false;pauseBtn.textContent='Pause';overlay.classList.add('hidden');placePlayer();previousTime=performance.now();cancelAnimationFrame(animationId);animationId=requestAnimationFrame(gameLoop)}
function gameLoop(now){if(!running||paused)return;const d=Math.min((now-previousTime)/1000,.04);previousTime=now;elapsed+=d;spawnClock+=d;const interval=Math.max(.38,.82-elapsed*.012);if(spawnClock>=interval){spawnClock=0;spawnRock()}timeEl.textContent=Math.max(0,Math.ceil(30-elapsed));const p={x:player.offsetLeft,y:player.offsetTop,w:player.offsetWidth,h:player.offsetHeight};[...rocks].forEach(r=>{r.y+=r.speed*d;r.rotation+=80*d;r.el.style.transform=`translate(${r.x}px,${r.y}px) rotate(${r.rotation}deg)`;const hit=r.x+r.size*.82>p.x&&r.x+r.size*.18<p.x+p.w&&r.y+r.size*.82>p.y&&r.y+r.size*.18<p.y+p.h;if(hit){score++;scoreEl.textContent=score;const pop=document.createElement('span');pop.className='pop-score';pop.textContent='+1';pop.style.left=`${p.x+p.w/2}px`;pop.style.top=`${p.y}px`;board.append(pop);setTimeout(()=>pop.remove(),700);removeRock(r)}else if(r.y>board.clientHeight+r.size)removeRock(r)});if(elapsed>=30)return finishGame();animationId=requestAnimationFrame(gameLoop)}
function togglePause(){if(!running)return;paused=!paused;pauseBtn.textContent=paused?'Resume':'Pause';if(paused){overlayTitle.textContent='Paused';overlayCopy.textContent='The rocks will wait for you.';overlayStart.textContent='Resume';overlay.classList.remove('hidden')}else{overlay.classList.add('hidden');previousTime=performance.now();animationId=requestAnimationFrame(gameLoop)}}
addEventListener('keydown',e=>{if(e.key==='ArrowLeft'||e.key.toLowerCase()==='a'){e.preventDefault();movePlayer(-.055)}if(e.key==='ArrowRight'||e.key.toLowerCase()==='d'){e.preventDefault();movePlayer(.055)}if(e.code==='Space'&&running){e.preventDefault();togglePause()}});document.getElementById('move-left').onpointerdown=()=>movePlayer(-.075);document.getElementById('move-right').onpointerdown=()=>movePlayer(.075);
function pointMove(e){if(!running||paused||e.pointerType==='mouse'&&e.buttons===0)return;const r=board.getBoundingClientRect();playerX=Math.max(0,Math.min(1,(e.clientX-r.left-player.offsetWidth/2)/(r.width-player.offsetWidth)));placePlayer()}board.onpointermove=pointMove;board.onpointerdown=e=>{if(!e.target.closest('button'))pointMove(e)};startBtn.onclick=startGame;pauseBtn.onclick=togglePause;overlayStart.onclick=()=>paused?togglePause():startGame();addEventListener('resize',placePlayer);document.addEventListener('visibilitychange',()=>{if(document.hidden&&running&&!paused)togglePause()});placePlayer();
